#For Linux and Colab
name: VAE-Emotion-Detection
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - https://repo.anaconda.com/pkgs/msys2
dependencies:
  - python=3.11.11
  - pip=25.1
  - bzip2
  - ca-certificates
  - libffi
  - openssl
  - setuptools
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
    - audioread==3.0.1
    - certifi==2025.4.26
    - cffi==1.17.1
    - charset-normalizer==3.4.2
    - decorator==5.2.1
    - filelock==3.18.0
    - fsspec==2025.3.2
    - idna==3.10
    - jinja2==3.1.6
    - joblib==1.5.0
    - lazy-loader==0.4
    - librosa==0.11.0
    - llvmlite==0.44.0
    - markupsafe==3.0.2
    - mpmath==1.3.0
    - msgpack==1.1.0
    - networkx==3.4.2
    - numba==0.61.2
    - numpy==2.2.6
    - packaging==25.0
    - pandas==2.2.3
    - platformdirs==4.3.8
    - pooch==1.8.2
    - pycparser==2.22
    - python-dateutil==2.9.0.post0
    - pytz==2025.2
    - requests==2.32.3
    - scikit-learn==1.6.1
    - scipy==1.15.3
    - six==1.17.0
    - soundfile==0.13.1
    - soxr==0.5.0.post1
    - sympy==1.14.0
    - threadpoolctl==3.6.0
    - torch==2.7.0
    - typing-extensions==4.13.2
    - tzdata==2025.2
    - urllib3==2.4.0